テンプレート部分の実装をおこなった
takenokoroid/old-support-tools pull request #9
Opened 2022-11-04 01:57 UTC by ifhito

# 変更の概要
テンプレートを作成しました
## やったこと
- jinja2 templateの作成
- jQueryでバリデーションの作成
- cssの作成
##変更内容
- ユーザIDを入力せずに送信するとエラー
- ユーザIDが先頭2文字英字+数字4桁になっていないとエラー
- 検索した後にCard要素で検索結果を返す
- その他、レイアウト作成
## 影響範囲
view部分のみ
## どうやるのか
以下のソースを`__init__.py`に追加し、`docker compose up`で表示させる(以下の関数はテスト用です)
```
@app.route("/", methods=['POST', 'GET'])
def hello_world():
    if request.method =='POST':
        id = request.form['userid']
        result = {
            "user": {
                "cgg_id": id,
                "name": 'test'
            },
            "service": {
                "deleted": True
            }
        }
        return render_template("index.html", result=result)
    else:
        return render_template("index.html")
```

## 備考
その他、デザインに気に入らない部分や機能的に足りない部分があったらお伝えください

2022-11-05 09:22 UTC, takenokoroid requested changes
プルリクありがとうございます。
動かしてみましたがjQueryによるヴァリデーションなど細かく動いていてよかったです。

いくつかレビューしました。
なにかあればコメントよろしくお願いいたします

2022-11-05 09:22 UTC, takenokoroid commented on webApp/flaskApp/templates/index.html
> +                <img alt="権限あり" data-toggle="tooltip" data-placement="top" title="権限あり" src="https://img.icons8.com/external-others-phat-plus/64/null/external-authentication-biometric-outline-others-
### what to do
- 「権限あり」を「利用中」に修正する
- 「権限なし」を「解除済み」に修正する
- roleに関するclass名などを修正

### why to do
おそらくDBにroleというカラムがあったため「権限あり」と表現しているかと思いますが、今回使用するdeletedはサービス利用を表現するため「利用中」が適切かなと思いました

2022-11-05 09:22 UTC, takenokoroid commented on webApp/flaskApp/templates/base.html
> +            <a class="navbar-brand" href="/">最強のサポートツール</a>
### what to do
- 「最強のサポートツール」を「最強防御セキュリティのサポートツール」に修正する

### why to do
とあるサービスのサポートツールということをより強調するヘッダーにしたいため
現状だと各種サービスをまとめるサポートツールと捉えることも可能なので

2022-11-05 10:53 UTC, ifhito commented on webApp/flaskApp/templates/index.html
> +                <img alt="権限あり" data-toggle="tooltip" data-placement="top" title="権限あり" src="https://img.icons8.com/external-others-phat-plus/64/null/external-authentication-biometric-outline-others-
deletedになってたのを忘れてました。
- Class名をrole => deletedに変更
- 権限あり => 利用中に変更
- 権限なし => 解除済みに変更
上記を行いました。
確認お願いします。

https://github.com/takenokoroid/old-support-tools/pull/9/commits/fdf8a931ed65e8d11ca2ddc4670d057f3ef06860

2022-11-05 10:54 UTC, ifhito commented on webApp/flaskApp/templates/base.html
> +            <a class="navbar-brand" href="/">最強のサポートツール</a>
修正しました。確認お願いします。

[be24b54](https://github.com/takenokoroid/old-support-tools/pull/9/commits/be24b54ffe4ff6e83a7b1fa795a1a2145ea626db)

2022-11-05 11:46 UTC, takenokoroid approved these changes
修正ありがとうございます
Approveします

2022-11-05 16:14 UTC, ifhito commented
一応、処理追加したので、確認お願いします

2022-11-07 11:40 UTC, takenokoroid commented
処理確認しました。
マージしてもよいかと思います

2022-11-07 12:10 UTC, merged